travis:
  secure:
    BINSTAR_TOKEN: q7Auv/fwXy4tLhSC2SG3aEyGSjn7dQYfWiAlZGH8BMRu3zw+ANg3wWfatAExLS+c6126o+YCV22+A2NaozeVJ2zbT7p9aQBb02/TWuzvrnFeedHDId9zRQHWSHlrRDZmLp6LiQpFf6hYMt4aSBHeCWPGTFL72fm4TYl3ZzSGkhRBLjVuS3UXMY1WfWu9G+n03tttC4iUWERNkj62BymUwiwcQzAw8U3cAEFiDFjFIViyLV9vFXoDgfniPB123fSnQ58MIHmvlbVyjoQT12FuddlBnQx23NIlr7wA9eLWVf3wXrKtKZfyH6lV4uZPAi/Bv1m46tEXVn6oDzCDIShcHUl1XjTHuDeq9U7dAFCcltlzcSzFJbgK19v4VCtfhjoq68CKYrqPm/PeElEVHSSV2omNOKBa7+LUQudKOYNwe9jaayTtF4NJ4zJLgoNDmH0jF+aUr85V8NGnw825o2mGbwguh4iB7CfeD1W8kFKtf2Pecg/EdtMgncV3dxZj4CWqb/Qvg3DpDodWNd3pAxf6CIkuFyZrYhlCWeNtjzfDlduH0Abtlje/YgMKWT5ZBEt9WgO5i8LN7+Y0IscfIX3SBlOzwu7XtKjMQSyscuCi5SUX25U0GqKIkBa9+2O8y7djUPSxNfwb0T7jgo2sk8RozW2S3gvQElqPDXgOSR4UhBQ=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
