travis:
  secure:
    BINSTAR_TOKEN: VL27B443htJQQbgN/MQEL//s3jykfYeajGmjSenSdGhXPxhiaaUQBjjXZMIXQbtcIsafxVXiGlviJExgz9HeSnhYp565Ph2yJbgSyAoWJlLYKAATLd7krCzD1c3vbAZOijxVddT4hMZefJZij/B+QqxzGCA1uNQAw7mpH0glgNN+6sWTI+tKR/4ZZxNSHG55SqQ6O2fP2GfXzIfeOXlXeWEiV4Dpr5KYM3Xdmm2lJoCnJacMgo63d/uVajmLXTDT3FEMARPEwKkycp6tJcPE6aRpUroEIOcLzzGa5ULcak9xVgPHT6th6VJ5WI+qTO84u2AUyyztGspsTRUXBxJI6G8ixtf+Teo5CxTxybU6oaDMD5ihrEW8RiDcTYVDTJux5RRcho2GCKm9apUhtZvTnWepaPGtpXdMSY4O9egfyTBSNcSNU29IZqq4oilBZF5OygCmVda9NkRewS5gYo4nX+cmcnoNREB2bxRM7H8cHLM/dpC7+dEaumwkmgqzhWipcaLiuXqtspEQiiA/WTab1w8mpDAIL2d+Fp7diW3lGivYeh/fcumHeliKnLEzze/suZIcLjyke2OjDsonrNa0vsM6LkqaOdAIQTMu9qzxNUuiqwHdjtriEXJz4NVCgIL45Igyteo5l2wfLKaOMEOpH147irnzlEUoVsYwau7psUM=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
